# Generated by Django 3.1 on 2022-05-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='state',
        ),
    ]
